Jonnitto:
  Plyr:
    # Pass an additional class to all plyr containers
    container: false
    include:
      # Include the files on every page, even when no plyr is present
      always: false
      # You can set file attributes like you can do in https://github.com/jonnitto/Carbon.IncludeAssets
      # If you set the value file to false, no css or js will be included
      javascript:
        file: 'plyr.min.js[defer]'
        assetPackage: 'Jonnitto.Plyr'
        assetPath: 'Public'
      css:
        file: 'plyr.css'
        assetPackage: 'Jonnitto.Plyr'
        assetPath: 'Public'
    selector:
      onDocument: false
      collection: '[instanceof Neos.Neos:ContentCollection]'
      content: '[instanceof Jonnitto.Plyr:Content]'
    progressiveEnhancement:
      YouTube: true
      Vimeo: true
    options:
      # Completely disable Plyr. This would allow you to do a User Agent check or
      # similar to programmatically enable or disable Plyr for a certain UA
      enabled: true
      # Display debugging information in the console
      debug: false
      # Autoplay the media on load. This is generally advised against on UX grounds.
      # It is also disabled by default in some browsers. If the autoplay attribute is
      # present on a <video> or <audio> element, this will be automatically set to true.
      autoplay: false
      # Only allow one player playing at once (Vimeo only)
      autopause: true
      # Allow inline playback on iOS (this effects YouTube/Vimeo - HTML5 requires the attribute present)
      playsinline: true
      # The time, in seconds, to seek when a user hits fast forward or rewind
      seekTime: 10
      # A number, between 0 and 1, representing the initial volume of the player
      volume: 1
      # Whether to start playback muted. If the muted attribute is present on a
      # <video> or <audio> element, this will be automatically set to true
      muted: false
      # Specify a custom duration for media
      duration: null
      # Displays the duration of the media on the "metadataloaded" event (on startup)
      # in the current time display. This will only work if the preload attribute is
      # not set to none (or is not set at all) and you choose not to display the
      # duration (see controls option).
      displayDuration: true
      # Display the current time as a countdown rather than an incremental counter
      invertTime: true
      # Clicking the currentTime inverts it's value to show time left rather than elapsed
      toggleInvert: true
      # The aspect ratio you want to use for embedded players
      ratio: '16:9'
      # Click (or tap) of the video container will toggle play/pause
      clickToPlay: true
      # Hide video controls automatically after 2s of no mouse or focus movement,
      # on control element blur (tab out), on playback start or entering fullscreen.
      # As soon as the mouse is moved, a control element is focused or playback is
      # paused, the controls reappear instantly
      hideControls: true
      # Reset to start when playback ended
      resetOnEnd: false
      # Disable right click menu on video to help as very primitive obfuscation
      # to prevent downloads of content
      disableContextMenu: true
      # Load the SVG sprite specified as the iconUrl option (if a URL).
      # If false, it is assumed you are handling sprite loading yourself.
      loadSprite: true
      # Specify the id prefix for the icons used in the default controls
      # (e.g. "plyr-play" would be "plyr"). This is to prevent clashes
      # if you're using your own SVG sprite but with the default controls.
      # Most people can ignore this option.
      iconPrefix: plyr
      # Specify a URL or path to the SVG sprite.
      # See https://github.com/sampotts/plyr#svg for more info
      iconUrl: '/_Resources/Static/Packages/Jonnitto.Plyr/plyr.svg'
      # Blank video (used to prevent errors on source change)
      blankVideo: '/_Resources/Static/Packages/Jonnitto.Plyr/blank.mp4'
      # Quality default
      quality:
        default: 576
        options:
          - 4320
          - 2880
          - 2160
          - 1440
          - 1080
          - 720
          - 576
          - 480
          - 360
          - 240
      loop:
        # Whether to loop the current video. If the loop attribute is present
        # on a <video> or <audio> element, this will be automatically set to
        # true This is an object to support future functionality
        active: false
      # Speed default and options to display
      speed:
        # The default speed for playback
        selected: 1
        # Options to display in the menu. Most browsers will refuse to play slower than 0.5
        options:
          - 0.5
          - 0.75
          - 1
          - 1.25
          - 1.5
          - 1.75
          - 2
      # Enable keyboard shortcuts for focused players only or globally
      # See https://github.com/sampotts/plyr#shortcuts for more info
      keyboard:
        focused: true
        global: false
      tooltips:
        # Display control labels as tooltips on :hover & :focus
        # (by default, the labels are screen reader only).
        controls: false
        # Display a seek tooltip to indicate on click where the media would seek to.
        seek: true
      # Captions settings
      captions:
        # Toggles if captions should be active by default.
        active: false
        # Sets the default language to load (if available)
        language: auto
        # Listen to new tracks added after Plyr is initialized.
        # This is needed for streaming captions, but may result in unselectable options
        update: false
      # Fullscreen settings
      fullscreen:
        # Toggles whether fullscreen should be enabled
        enabled: true
        # Allow fallback to a full-window solution
        fallback: true
        # whether to use native iOS fullscreen when entering
        # fullscreen (no custom controls)
        iosNative: false

      # Local storage
      storage:
        # Allow use of local storage to store user settings
        enabled: true
        # The key name to use
        key: plyr
      # See https://github.com/sampotts/plyr/blob/master/controls.md for more information
      controls:
        - play-large # The large play button in the center
        # - restart # Restart playback
        # - rewind # Rewind by the seek time (default 10 seconds)
        - play # Play/pause playback
        # - fast-forward # Fast forward by the seek time (default 10 seconds)
        - progress # The progress bar and scrubber for playback and buffering
        - current-time # The current time of playback
        # - duration # The full duration of the media
        - mute # Toggle mute
        - volume # Volume control
        - captions # Toggle captions
        - settings # Settings menu
        - pip # Picture-in-picture (currently Safari only)
        - airplay # Airplay (currently Safari only)
        - fullscreen # Toggle fullscreen
      # If you're using the default controls are used then you can specify which settings to show in the menu
      settings:
        - captions
        - quality
        - speed
      # Allows binding of event listeners to the controls before the default handlers.
      # If your handler prevents default on the event
      # (event.preventDefault()), the default handler will not fire.
      listeners:
        seek: null
        play: null
        pause: null
        restart: null
        rewind: null
        fastForward: null
        mute: null
        volume: null
        captions: null
        fullscreen: null
        pip: null
        airplay: null
        speed: null
        quality: null
        loop: null
        language: null
      # API keys
      keys:
        google: null
      # Advertisements plugin
      # Register for an account here: http://vi.ai/publisher-video-monetization/?aid=plyrio
      ads:
        # Whether to enable vi.ai ads
        enabled: false
        # Your unique vi.ai publisher ID
        publisherId: ''
      # YouTube plugin
      youtube:
        # Whether to use an alternative version of YouTube without cookies
        noCookie: false
        # No related vids
        rel: null
        # Hide info
        showinfo: null
        # Hide annotations
        ivLoadPolicy: null
        # Hide logos as much as possible (they still show one in the corner when paused)
        modestbranding: null

Neos:
  Neos:
    userInterface:
      translation:
        autoInclude:
          Jonnitto.Plyr:
            - 'NodeTypes/*'
    nodeTypes:
      groups:
        multimedia:
          position: 200
          label: 'Jonnitto.Plyr:NodeTypes.Groups:multimedia'
    fusion:
      autoInclude:
        Jonnitto.Plyr: true
