
Jonnitto:
  Plyr:
    alwaysInclude: false
    includeJavascript: true
    includeCSS: true
    selector:
      collection: '[instanceof Neos.Neos:ContentCollection]'
      content: '[instanceof Jonnitto.Plyr:Content]'
    options:
      controls: '[''play-large'',''play'',''progress'',''current-time'',''mute'',''volume'',''captions'',''fullscreen'']'
      autoplay: false
      seekTime: 10
      volume: 10
      clickToPlay: true
      hideControls: true
      showPosterOnEnd: false
      tooltips:
        controls: false
        seek: true
      displayDuration: true
      fullscreen:
        enabled: true
        fallback: true
        allowAudio: false
Neos:
  Neos:
    typoScript:
      autoInclude:
        Jonnitto.Plyr: true
    userInterface:
      translation:
        autoInclude:
          Jonnitto.Plyr:
            - 'NodeTypes/*'
    nodeTypes:
      groups:
        multimedia:
          position: 200
          label: 'Jonnitto.Plyr:NodeTypes.Groups:multimedia'
